### ISSUE TITLE
Add an announcement area on the home page

### ISSUE THREAD

**Issue by redben** [loomnetwork/dashboard#1198]
- [x] On the right column of the page 
- [x] 300 x 250
- [x] Make sure it adapts to mobile
- [x] content and state (on/off) toggle from config.announcements.home

**Comment by yuneeksehgal** [comment]
Announcement area is not showing for following urls. This is basically happens when user try to access My account from Validators page.

https://dev-dashboard.dappchains.com/login?redirect=%2Faccount

![image](https://user-images.githubusercontent.com/23660413/64171393-2c83b980-ce70-11e9-9a07-61d92ac9ff3b.png)

**Comment by yuneeksehgal** [comment]
This is looking good now
