### ISSUE TITLE
Show user accounts in a safe way

### ISSUE THREAD

**Issue by gakonst** [loomnetwork/dashboard#151]
Earlier we disabled showing addresses because people messed it up and sent ethereum funds to the dappchain address

![image](https://user-images.githubusercontent.com/17802178/53476337-cd855800-3a7a-11e9-9bad-4cf25980f451.png)

Can we show the user's dappchain address and ethereum address to the UIs in a safe way without them confusing which is which?

An obvious solution would be to show the addresses with the chainId prefix, ie `plasma:0x...`, `eth:...`, although people may confuse the plasma address with ethereum one given how the word plasma is primarily connected to ethereum

**Comment by cimtrae** [comment]
I think plasma suffix is good enough. If we want to be really clear it can say "Loom Plasmachain Account:"
Another option is hide the plasmachain address under a link and when the user clicks is it shows plasma address in a popup. ETH is displayed directly alsthough the captio could say "Mapped to mainchain ethereum account:"

**Comment by fkbenjamin** [comment]
You could change the prefix for PlasmaChain accounts to `loomx` instead of `0x` in the frontend. Then you could display them, but no one who doesn't know what he is doing would be able to send ethereum funds to that address (almost all wallets check for the validity of an address and this would not be valid for this check)

So you could display it like this:
```
eth: 0x1a2bc4....
plasma: loomx9z8y7s
```

under the hood, the plasma address would still be `0x9z8y7s`, but it would be obvious that this is a Loom address and not an Ethereum one.
