### ISSUE TITLE
Moving from one tab to another, Withdraw section is allowing user for another withdraw even it has incomplete withdraw

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#242]
Video Link: https://slack-files.com/T7AB1S3LN-FGSLWQUHY-88b38fbbd6

**Comment by redben** [comment]
There are two way:
- either we only allow one tab to be open by using localStorage check 
- or we keep tabs in sync using BroadcastChannel.
Either ways, it is still not fool proof as we running on a browser.

On the other hand we can catch the error if the gateway throws one and tell the user that the transaction failed because there was an ongoing transfer
